### ISSUE TITLE
Escaped parentheses throw out regex in yaml.

### ISSUE THREAD

**Issue by SSlinky** [pedro-w/vscode-tmlanguage#11]
![image](https://user-images.githubusercontent.com/39886505/189537821-212731df-d7e1-49da-83d7-7b922a43d2e4.png)

**Comment by SSlinky** [comment]
You can work around this by using a comment to close the group.
![image](https://user-images.githubusercontent.com/39886505/189538003-27e9fe42-d782-47ce-bfa3-68b800336b0a.png)

**Comment by pedro-w** [comment]
Hi Sam, thanks for this. Please can you explain a bit more about what you're doing and attach/link to the file that's causing problems?
Cheers!

**Comment by SSlinky** [comment]
The TM grammar for yaml is matching on escaped parentheses as if it's the beginning of a new group. Multiple examples in [this file](https://github.com/SSlinky/VBA-LanguageServer/blob/master/client/src/syntaxes/vba.tmLanguage.yaml).

**Comment by pedro-w** [comment]
I have pushed an update which I believe will address this. Are you able to test?

**Comment by SSlinky** [comment]
Looks to be resolved to me, thanks!

**Comment by pedro-w** [comment]
Thanks for reporting!

Fixed by 0aa687c4e1a60ce5e186461c598912531a84ae14

**Comment by pedro-w** [comment]
@SSlinky did this fix your other issues #13  and #12 ?

**Comment by SSlinky** [comment]
No, neither of those issues appear to have been addressed.
