### ISSUE TITLE
The `uuid` package triggers false positive in JSON files

### ISSUE THREAD

**Issue by dnicolson** [pedro-w/vscode-tmlanguage#17]
A JSON file containing the following:
```json
{
  "dependencies": {
    "uuid": "^9.0.0"
  }
}
```

Results in:
![Screenshot 2023-08-08 at 21 31 55](https://github.com/pedro-w/vscode-tmlanguage/assets/2276355/e34a020a-aaf5-46ef-969c-256aedffc773)

**Comment by pedro-w** [comment]
I'll look into it. What version of the extension are you using?

**Comment by dnicolson** [comment]
Version v0.13.0.

**Comment by pedro-w** [comment]
I see what you mean. Looks like the extension is being activated on ordinary json files which it shouldn't be.

**Comment by pedro-w** [comment]
I've stopped the extension activating on all .json, .yaml and .xml files, now it's just .tmLanguage.json, .JSON-tmLanguage, .tmLanguage.yaml, .YAML-tmLanguage,          .tmLanguage.yaml and .tmLanguage. I think this is the right thing to do even if it's a bit unsubtle. 
See bf6d918
If you can test it yourself, great, otherwise I'll publish a new version in the next few days.

**Comment by pedro-w** [comment]
@dnicolson new version 0.14.0 has been uploaded to the marketplace, if you've got time please can you tell me if it fixes this issue!

**Comment by dnicolson** [comment]
Version 0.14.0 resolves the issue.

Initially, I wasn't able to reproduce the original issue because the diagnostics are only run after file changes. Is this intentional? If not, adding this to `extension.ts` will check files before changes are made (`onDidOpenTextDocument` is not called when a workspace is reopened):
```
    const document = vscode.workspace.textDocuments[0];
    if (document) {
      diagnosticProvider.CreateDiagnostics(document);
    }
    vscode.workspace.onDidOpenTextDocument(document => {
      diagnosticProvider.CreateDiagnostics(document)
    })
```

**Comment by pedro-w** [comment]
I haven't had time to dig into this, but I think it's not working properly in fact - if you have a folder with a `.tmlanguage.json` file and a 'plain' `.json` file, the extension will not activate until you open the former but then it will attach diagnostics to both of them. The fix may be just checking the document's `languageId` before proceeding.
