### ISSUE TITLE
Publish vscode-tmlanguage in Marketplace

### ISSUE THREAD

**Issue by texastoland** [pedro-w/vscode-tmlanguage#3]
The upstream repo is archived. Would you mind publishing your fixes? And either merging Togusa09/vscode-tmlanguage#28 or making it configurable? I appreciate what you've done!

**Comment by pedro-w** [comment]
Thanks, I've transferred this to the correct repository!

**Comment by texastoland** [comment]
I've been using your last version for a few days already 🙏🏼 Everything working smoothly. There are a couple highlighting bugs in YAML related to comments. I'll open a separate issue and happy to fix it myself.

**Comment by pedro-w** [comment]
Sorry for the delay. I was merging https://github.com/Togusa09/vscode-tmlanguage/pull/28 but it doesn't work quite right; specifically when you convert a file it strips the extension and adds the new one, but a file like `something.tmlanguage.json` has two extensions so you end up with a converted file like `something.tmlanguage.tmlanguage.yaml`. (this was OK before because the extension was `.JSON-tmlanguage` - that's one extension)
I know how to fix it, but if someone else wants they can jump in.

**Comment by texastoland** [comment]
I'll PR in the next couple days 👌🏼

**Comment by pedro-w** [comment]
I have published it now as v0.11.0 and hopefully we can follow up before long with a version including the change to the extensions.

**Comment by texastoland** [comment]
You can add https://marketplace.visualstudio.com/items?itemName=pedro-w.tmlanguage to the GitHub page! I [tweeted](https://twitter.com/texastoland/status/1439561877621592068?s=20) it too 🍾 Sorry I came down ill for a few days in the middle of a frustrating TextMate bug. I haven't forgotten 🤞🏼

**Comment by ghost** [comment]
Is Togusa09#28 live in ths repository?

**Comment by pedro-w** [comment]
Not yet because texastoland has been ill and not able to fix it (there are some problems with https://github.com/Togusa09/vscode-tmlanguage/pull/28 as it is currently).

**Comment by texastoland** [comment]
I finally finished my other PR. I'll see how far I get this weekend 🤞🏼

**Comment by pedro-w** [comment]
OK, I've made a new branch containing (most of) https://github.com/Togusa09/vscode-tmlanguage/pull/28 - unfortunately @SNDST00M deleted the source repo so I had to redo it by hand. It's in https://github.com/pedro-w/vscode-tmlanguage/tree/file-extensions for the moment.

**Comment by ghost** [comment]
I do believe adding .patch to URL and using `git apply` works better.
