### ISSUE TITLE
Error with any of the conversion commands

### ISSUE THREAD

**Issue by nriley** [pedro-w/vscode-tmlanguage#9]
I get the following:

```Command 'Convert to tmLanguage JSON File' resulted in an error (command 'extension.convertToJsonTml' not found)```

Not sure what to do with this. I am pretty new to VS Code so not sure how to debug further.

**Comment by pedro-w** [comment]
Hi, sorry I've only just seen this (for some reason I didn't get notified) Sounds like the extension is not registering itself properly. What version of VSCode are you using (and are you using the latest version of the extension, 0.12.0?)

**Comment by nriley** [comment]
I was able to convert it another way. Thanks for following up though (and sorry for not closing this earlier!)
